services:
  word-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
  
  console-search-service:
    build:
      context: .
      dockerfile: ConsoleSearch/Dockerfile
    depends_on: 
      - word-service
    stdin_open: true
    tty: true
  
  indexer-service:
    build:
      context: .
      dockerfile: Indexer/Dockerfile
    depends_on: 
      - word-service
  
  word-service:
    build:
      context: .
      dockerfile: WordService/Dockerfile
    depends_on: 
      - word-db

volumes:
  mssql-data: